#!/usr/bin/env bash
# ============================================================
# VulnPilot AI - One-Click Setup Wizard
#
# Run: bash setup.sh
#
# This wizard:
#   1. Detects your environment
#   2. Asks what integrations you want
#   3. Auto-generates your .env file
#   4. Starts everything with docker compose
#   5. Runs health checks to verify all connections
#   6. Opens the dashboard
#
# Total time: ~3 minutes
# ============================================================

set -e

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; PURPLE='\033[0;35m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'

clear
echo -e "${PURPLE}${BOLD}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║              🛡️  VulnPilot AI - Setup Wizard                 ║"
echo "║              Solvent CyberSecurity                           ║"
echo "║                                                              ║"
echo "║   Zero Noise. Zero Delay. Zero Missed Patches.              ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ─── Preflight Checks ───
echo -e "${CYAN}[1/7] Checking prerequisites...${NC}"
MISSING=""
command -v docker >/dev/null 2>&1 || MISSING="$MISSING docker"
command -v docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 || MISSING="$MISSING docker-compose"
if [ -n "$MISSING" ]; then
    echo -e "${RED}Missing required tools:${MISSING}${NC}"
    echo "Install Docker Desktop: https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "${GREEN}  ✅ Docker found: $(docker --version | head -1)${NC}"

# Check if .env already exists
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}  ⚠️  Existing .env found. Back up as .env.backup${NC}"
    cp "$ENV_FILE" ".env.backup.$(date +%s)"
fi

# ─── Choose Deployment Profile ───
echo ""
echo -e "${CYAN}[2/7] Choose your deployment profile:${NC}"
echo ""
echo -e "  ${GREEN}1) Free / Air-Gapped ${NC}- \$0/mo, everything local"
echo "     Ollama AI + OpenVAS + Wazuh + CSV CMDB + Console tickets"
echo ""
echo -e "  ${BLUE}2) Developer / Testing ${NC}- \$0/mo, free trials + sandboxes"
echo "     Ollama AI + Free APIs (EPSS/KEV/NVD) + ServiceNow PDI + Jira Free"
echo ""
echo -e "  ${PURPLE}3) Production / Enterprise ${NC}- ~\$200-500/mo"
echo "     Claude AI + GPT Challenger + Tenable + ServiceNow + Slack/Teams"
echo ""
echo -e "  ${YELLOW}4) Custom ${NC}- Pick each integration yourself"
echo ""
read -p "  Choose [1-4]: " PROFILE

# ─── Initialize env vars ───
cat > "$ENV_FILE" << 'HEADER'
# ============================================================
# VulnPilot AI - Auto-generated by setup.sh
# Re-run 'bash setup.sh' anytime to reconfigure
# ============================================================

HEADER

# Defaults
LLM="ollama"
CHALLENGER=""
SCANNERS=""
TICKETS="console"
THREATINTEL="local"
CMDB="csv"
NOTIFY="console"
OPENVAS_ENABLED="no"
WAZUH_ENABLED="no"

case "$PROFILE" in
    1)
        echo -e "${GREEN}  → Free / Air-Gapped selected${NC}"
        LLM="ollama"; SCANNERS="openvas,wazuh"; TICKETS="console"
        THREATINTEL="local"; CMDB="csv"; NOTIFY="console"
        OPENVAS_ENABLED="yes"; WAZUH_ENABLED="yes"
        ;;
    2)
        echo -e "${BLUE}  → Developer / Testing selected${NC}"
        LLM="ollama"; SCANNERS="openvas"; TICKETS="console"
        THREATINTEL="api"; CMDB="csv"; NOTIFY="console"
        OPENVAS_ENABLED="yes"

        echo ""
        echo -e "${CYAN}  Optional: Add free sandboxes?${NC}"
        read -p "  ServiceNow PDI? (y/n) [n]: " SN
        if [[ "$SN" =~ ^[Yy] ]]; then
            TICKETS="servicenow"
            read -p "    Instance URL (e.g. dev12345.service-now.com): " SN_INST
            read -p "    Username [admin]: " SN_USER; SN_USER=${SN_USER:-admin}
            read -p "    Password: " SN_PASS
            CMDB="servicenow"
        fi

        read -p "  Jira Free Tier? (y/n) [n]: " JR
        if [[ "$JR" =~ ^[Yy] ]]; then
            if [ "$TICKETS" = "console" ]; then TICKETS="jira"; fi
            read -p "    Jira URL (e.g. https://yourname.atlassian.net): " JIRA_URL
            read -p "    Email: " JIRA_EMAIL
            read -p "    API Token: " JIRA_TOKEN
            read -p "    Project Key [SEC]: " JIRA_PROJECT; JIRA_PROJECT=${JIRA_PROJECT:-SEC}
        fi
        ;;
    3)
        echo -e "${PURPLE}  → Production / Enterprise selected${NC}"
        LLM="anthropic"; CHALLENGER="openai"
        TICKETS="servicenow"; THREATINTEL="api"
        CMDB="servicenow"; NOTIFY="slack"

        echo ""
        echo -e "${CYAN}  AI Provider Keys:${NC}"
        read -p "    Anthropic API Key (sk-ant-...): " ANTHROPIC_KEY
        read -p "    OpenAI API Key (sk-...): " OPENAI_KEY

        echo ""
        echo -e "${CYAN}  Scanner Configuration:${NC}"
        read -p "    Tenable Access Key: " TEN_ACCESS
        read -p "    Tenable Secret Key: " TEN_SECRET
        SCANNERS="tenable"

        read -p "    Add Qualys? (y/n) [n]: " QA
        if [[ "$QA" =~ ^[Yy] ]]; then
            SCANNERS="$SCANNERS,qualys"
            read -p "    Qualys API URL [https://qualysapi.qualys.com]: " QA_URL; QA_URL=${QA_URL:-https://qualysapi.qualys.com}
            read -p "    Qualys Username: " QA_USER
            read -p "    Qualys Password: " QA_PASS
        fi

        read -p "    Add Wazuh for real-time? (y/n) [y]: " WZ; WZ=${WZ:-y}
        if [[ "$WZ" =~ ^[Yy] ]]; then
            SCANNERS="$SCANNERS,wazuh"
            WAZUH_ENABLED="yes"
            read -p "    Wazuh API URL [https://localhost:55000]: " WZ_URL; WZ_URL=${WZ_URL:-https://localhost:55000}
            read -p "    Wazuh Username [wazuh-wui]: " WZ_USER; WZ_USER=${WZ_USER:-wazuh-wui}
            read -p "    Wazuh Password: " WZ_PASS
        fi

        echo ""
        echo -e "${CYAN}  ServiceNow:${NC}"
        read -p "    Instance URL: " SN_INST
        read -p "    Username: " SN_USER
        read -p "    Password: " SN_PASS

        echo ""
        echo -e "${CYAN}  Notifications:${NC}"
        echo "    1) Slack  2) Teams  3) Email  4) PagerDuty  5) Webhook  6) Console"
        read -p "    Choose [1-6]: " NOTIF_CHOICE
        case "$NOTIF_CHOICE" in
            1) NOTIFY="slack"; read -p "    Slack Webhook URL: " SLACK_URL ;;
            2) NOTIFY="teams"; read -p "    Teams Webhook URL: " TEAMS_URL ;;
            3) NOTIFY="email"
               read -p "    SMTP Host [smtp.gmail.com]: " SMTP_HOST; SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
               read -p "    SMTP Port [587]: " SMTP_PORT; SMTP_PORT=${SMTP_PORT:-587}
               read -p "    SMTP User: " SMTP_USER
               read -p "    SMTP Password: " SMTP_PASS
               read -p "    From Address: " SMTP_FROM ;;
            4) NOTIFY="console"; read -p "    PagerDuty Routing Key: " PD_KEY ;;
            5) NOTIFY="webhook"; read -p "    Webhook URL: " WEBHOOK_URL ;;
            *) NOTIFY="console" ;;
        esac
        ;;
    4)
        echo -e "${YELLOW}  → Custom configuration${NC}"
        echo ""

        # LLM
        echo -e "${CYAN}  AI Provider:${NC}"
        echo "    1) Ollama (free, local)  2) Claude (cloud)  3) GPT-4o (cloud)"
        read -p "    Choose [1-3]: " LLM_CHOICE
        case "$LLM_CHOICE" in
            2) LLM="anthropic"; read -p "    Anthropic API Key: " ANTHROPIC_KEY ;;
            3) LLM="openai"; read -p "    OpenAI API Key: " OPENAI_KEY ;;
            *) LLM="ollama" ;;
        esac

        read -p "  Cross-model Challenger? (y/n) [n]: " CH
        if [[ "$CH" =~ ^[Yy] ]]; then
            echo "    1) OpenAI  2) Claude  3) Ollama"
            read -p "    Challenger [1-3]: " CH_CHOICE
            case "$CH_CHOICE" in
                1) CHALLENGER="openai"
                   if [ -z "$OPENAI_KEY" ]; then read -p "    OpenAI API Key: " OPENAI_KEY; fi ;;
                2) CHALLENGER="anthropic"
                   if [ -z "$ANTHROPIC_KEY" ]; then read -p "    Anthropic API Key: " ANTHROPIC_KEY; fi ;;
                3) CHALLENGER="ollama" ;;
            esac
        fi

        # Scanners
        echo ""
        echo -e "${CYAN}  Scanners (select all that apply):${NC}"
        read -p "    OpenVAS (free)? (y/n) [y]: " S1; S1=${S1:-y}
        [[ "$S1" =~ ^[Yy] ]] && SCANNERS="openvas" && OPENVAS_ENABLED="yes"

        read -p "    Wazuh (free, real-time)? (y/n) [y]: " S2; S2=${S2:-y}
        if [[ "$S2" =~ ^[Yy] ]]; then
            SCANNERS="${SCANNERS:+$SCANNERS,}wazuh"; WAZUH_ENABLED="yes"
        fi

        read -p "    Tenable.io? (y/n) [n]: " S3
        if [[ "$S3" =~ ^[Yy] ]]; then
            SCANNERS="${SCANNERS:+$SCANNERS,}tenable"
            read -p "    Access Key: " TEN_ACCESS
            read -p "    Secret Key: " TEN_SECRET
        fi

        read -p "    Qualys? (y/n) [n]: " S4
        if [[ "$S4" =~ ^[Yy] ]]; then
            SCANNERS="${SCANNERS:+$SCANNERS,}qualys"
            read -p "    API URL [https://qualysapi.qualys.com]: " QA_URL; QA_URL=${QA_URL:-https://qualysapi.qualys.com}
            read -p "    Username: " QA_USER
            read -p "    Password: " QA_PASS
        fi

        read -p "    Rapid7? (y/n) [n]: " S5
        if [[ "$S5" =~ ^[Yy] ]]; then
            SCANNERS="${SCANNERS:+$SCANNERS,}rapid7"
            read -p "    API Key: " R7_KEY
            read -p "    Region [us]: " R7_REGION; R7_REGION=${R7_REGION:-us}
        fi

        read -p "    Nessus file import? (y/n) [n]: " S6
        [[ "$S6" =~ ^[Yy] ]] && SCANNERS="${SCANNERS:+$SCANNERS,}nessus_file"

        [ -z "$SCANNERS" ] && SCANNERS="openvas" && OPENVAS_ENABLED="yes"

        # Tickets
        echo ""
        echo -e "${CYAN}  Ticket Provider:${NC}"
        echo "    1) Console (dev)  2) ServiceNow  3) Jira"
        read -p "    Choose [1-3]: " TK
        case "$TK" in
            2) TICKETS="servicenow"
               read -p "    Instance URL: " SN_INST
               read -p "    Username: " SN_USER
               read -p "    Password: " SN_PASS ;;
            3) TICKETS="jira"
               read -p "    Jira URL: " JIRA_URL
               read -p "    Email: " JIRA_EMAIL
               read -p "    API Token: " JIRA_TOKEN
               read -p "    Project Key [SEC]: " JIRA_PROJECT; JIRA_PROJECT=${JIRA_PROJECT:-SEC} ;;
            *) TICKETS="console" ;;
        esac

        # Threat Intel
        echo ""
        echo -e "${CYAN}  Threat Intelligence:${NC}"
        echo "    1) Local CSV (offline)  2) Live APIs (free)"
        read -p "    Choose [1-2]: " TI
        case "$TI" in
            2) THREATINTEL="api" ;;
            *) THREATINTEL="local" ;;
        esac

        # CMDB
        echo ""
        echo -e "${CYAN}  CMDB:${NC}"
        echo "    1) CSV file (built-in)  2) ServiceNow CMDB"
        read -p "    Choose [1-2]: " CM
        case "$CM" in
            2) CMDB="servicenow"
               if [ -z "$SN_INST" ]; then
                   read -p "    Instance URL: " SN_INST
                   read -p "    Username: " SN_USER
                   read -p "    Password: " SN_PASS
               fi ;;
            *) CMDB="csv" ;;
        esac

        # Notifications
        echo ""
        echo -e "${CYAN}  Notifications:${NC}"
        echo "    1) Console  2) Slack  3) Teams  4) Email  5) Webhook"
        read -p "    Choose [1-5]: " NF
        case "$NF" in
            2) NOTIFY="slack"; read -p "    Slack Webhook URL: " SLACK_URL ;;
            3) NOTIFY="teams"; read -p "    Teams Webhook URL: " TEAMS_URL ;;
            4) NOTIFY="email"
               read -p "    SMTP Host [smtp.gmail.com]: " SMTP_HOST; SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
               read -p "    SMTP Port [587]: " SMTP_PORT; SMTP_PORT=${SMTP_PORT:-587}
               read -p "    SMTP User: " SMTP_USER
               read -p "    SMTP Password: " SMTP_PASS
               read -p "    From Address: " SMTP_FROM ;;
            5) NOTIFY="webhook"; read -p "    Webhook URL: " WEBHOOK_URL ;;
            *) NOTIFY="console" ;;
        esac
        ;;
esac

# ─── Generate .env ───
echo ""
echo -e "${CYAN}[3/7] Generating .env configuration...${NC}"

cat >> "$ENV_FILE" << EOF
# --- LLM Provider ---
LLM_PROVIDER=$LLM
EOF

[ "$LLM" = "ollama" ] && cat >> "$ENV_FILE" << 'EOF'
OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL=llama3.2:8b
EOF

[ "$LLM" = "anthropic" ] && cat >> "$ENV_FILE" << EOF
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
ANTHROPIC_MODEL=claude-sonnet-4-20250514
EOF

[ "$LLM" = "openai" ] && cat >> "$ENV_FILE" << EOF
OPENAI_API_KEY=$OPENAI_KEY
OPENAI_MODEL=gpt-4o
EOF

if [ -n "$CHALLENGER" ]; then
    echo "CHALLENGER_PROVIDER=$CHALLENGER" >> "$ENV_FILE"
    [ "$CHALLENGER" = "openai" ] && [ -n "$OPENAI_KEY" ] && echo "OPENAI_API_KEY=$OPENAI_KEY" >> "$ENV_FILE"
    [ "$CHALLENGER" = "anthropic" ] && [ -n "$ANTHROPIC_KEY" ] && echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY" >> "$ENV_FILE"
else
    echo "CHALLENGER_PROVIDER=" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# --- Scanners ---
SCANNER_PROVIDERS=$SCANNERS
EOF

[ -n "$TEN_ACCESS" ] && cat >> "$ENV_FILE" << EOF
TENABLE_ACCESS_KEY=$TEN_ACCESS
TENABLE_SECRET_KEY=$TEN_SECRET
EOF

[ -n "$QA_USER" ] && cat >> "$ENV_FILE" << EOF
QUALYS_API_URL=${QA_URL:-https://qualysapi.qualys.com}
QUALYS_USERNAME=$QA_USER
QUALYS_PASSWORD=$QA_PASS
EOF

[ -n "$R7_KEY" ] && cat >> "$ENV_FILE" << EOF
RAPID7_API_KEY=$R7_KEY
RAPID7_REGION=${R7_REGION:-us}
EOF

[[ "$SCANNERS" == *"openvas"* ]] && cat >> "$ENV_FILE" << 'EOF'
OPENVAS_HOST=openvas
OPENVAS_PORT=9390
OPENVAS_USER=admin
OPENVAS_PASSWORD=admin
EOF

[[ "$SCANNERS" == *"wazuh"* ]] && cat >> "$ENV_FILE" << EOF
WAZUH_API_URL=${WZ_URL:-https://wazuh-manager:55000}
WAZUH_USERNAME=${WZ_USER:-wazuh-wui}
WAZUH_PASSWORD=${WZ_PASS:-wazuh}
WAZUH_VERIFY_SSL=false
EOF

[[ "$SCANNERS" == *"nessus_file"* ]] && echo "NESSUS_FILE_PATH=./data/sample_scans/" >> "$ENV_FILE"

cat >> "$ENV_FILE" << EOF

# --- Tickets ---
TICKET_PROVIDER=$TICKETS
EOF

[ "$TICKETS" = "servicenow" ] && cat >> "$ENV_FILE" << EOF
SERVICENOW_INSTANCE=https://$SN_INST
SERVICENOW_USERNAME=$SN_USER
SERVICENOW_PASSWORD=$SN_PASS
EOF

[ "$TICKETS" = "jira" ] && cat >> "$ENV_FILE" << EOF
JIRA_URL=$JIRA_URL
JIRA_EMAIL=$JIRA_EMAIL
JIRA_API_TOKEN=$JIRA_TOKEN
JIRA_PROJECT_KEY=${JIRA_PROJECT:-SEC}
EOF

cat >> "$ENV_FILE" << EOF

# --- Threat Intelligence ---
THREATINTEL_MODE=$THREATINTEL
EPSS_CSV_PATH=./data/epss_scores.csv
KEV_JSON_PATH=./data/known_exploited_vulns.json
EOF

cat >> "$ENV_FILE" << EOF

# --- CMDB ---
CMDB_PROVIDER=$CMDB
CMDB_FILE_PATH=./data/cmdb_assets.csv
EOF

cat >> "$ENV_FILE" << EOF

# --- Notifications ---
NOTIFICATION_CHANNEL=$NOTIFY
EOF

[ -n "$SLACK_URL" ] && echo "SLACK_WEBHOOK_URL=$SLACK_URL" >> "$ENV_FILE"
[ -n "$TEAMS_URL" ] && echo "TEAMS_WEBHOOK_URL=$TEAMS_URL" >> "$ENV_FILE"
[ -n "$SMTP_HOST" ] && cat >> "$ENV_FILE" << EOF
SMTP_HOST=$SMTP_HOST
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=$SMTP_USER
SMTP_PASSWORD=$SMTP_PASS
SMTP_FROM=${SMTP_FROM:-vulnpilot@company.com}
EOF
[ -n "$PD_KEY" ] && echo "PAGERDUTY_ROUTING_KEY=$PD_KEY" >> "$ENV_FILE"
[ -n "$WEBHOOK_URL" ] && cat >> "$ENV_FILE" << EOF
WEBHOOK_URL=$WEBHOOK_URL
EOF

cat >> "$ENV_FILE" << 'EOF'

# --- Database ---
DATABASE_URL=postgresql+asyncpg://vulnpilot:dev@postgres:5432/vulnpilot
DATABASE_URL_SYNC=postgresql://vulnpilot:dev@postgres:5432/vulnpilot

# --- Redis ---
REDIS_URL=redis://redis:6379/0

# --- Application ---
APP_NAME=VulnPilot AI
APP_ENV=development
LOG_LEVEL=info
API_HOST=0.0.0.0
API_PORT=8000
SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || echo "change-this-secret-key-$(date +%s)")
AUTH_PROVIDER=none

# --- VPRS Config ---
VPRS_WEIGHTS_PATH=./config/vprs_weights.yaml
HARD_RULES_PATH=./config/hard_rules.yaml
SLA_TIERS_PATH=./config/sla_tiers.yaml

# --- Drift Detector (Lock 3) ---
DRIFT_CHECK_INTERVAL_HOURS=6
EOF

echo -e "${GREEN}  ✅ .env generated with $(wc -l < $ENV_FILE) lines${NC}"

# ─── Generate docker-compose override for optional services ───
echo -e "${CYAN}[4/7] Configuring Docker services...${NC}"

COMPOSE_OVERRIDE="docker-compose.override.yml"
if [ "$OPENVAS_ENABLED" = "yes" ] || [ "$WAZUH_ENABLED" = "yes" ]; then
    cat > "$COMPOSE_OVERRIDE" << 'OVERRIDE_HEADER'
# Auto-generated by setup.sh - additional scanning services
services:
OVERRIDE_HEADER

    if [ "$OPENVAS_ENABLED" = "yes" ]; then
        cat >> "$COMPOSE_OVERRIDE" << 'OPENVAS_SVC'
  openvas:
    image: greenbone/community-edition:stable
    ports:
      - "9392:9392"
    volumes:
      - openvas_data:/data
    restart: unless-stopped
OPENVAS_SVC
        echo -e "${GREEN}  ✅ OpenVAS added to Docker stack${NC}"
    fi

    if [ "$WAZUH_ENABLED" = "yes" ]; then
        cat >> "$COMPOSE_OVERRIDE" << 'WAZUH_SVC'
  wazuh-manager:
    image: wazuh/wazuh-manager:4.9.2
    hostname: wazuh-manager
    ports:
      - "55000:55000"
      - "1514:1514"
      - "1515:1515"
    volumes:
      - wazuh_data:/var/ossec/data
    environment:
      WAZUH_API_USER: wazuh-wui
      WAZUH_API_PASSWORD: wazuh
    restart: unless-stopped
WAZUH_SVC
        echo -e "${GREEN}  ✅ Wazuh added to Docker stack${NC}"
    fi
else
    rm -f "$COMPOSE_OVERRIDE"
fi

# ─── Start Services ───
echo ""
echo -e "${CYAN}[5/7] Starting VulnPilot AI...${NC}"
echo ""

# Handle GPU for Ollama
if [ "$LLM" = "ollama" ]; then
    if command -v nvidia-smi >/dev/null 2>&1; then
        echo -e "${GREEN}  NVIDIA GPU detected - Ollama will use GPU acceleration${NC}"
    else
        echo -e "${YELLOW}  No NVIDIA GPU - Ollama will use CPU (slower, but works)${NC}"
        # Remove GPU reservation from docker-compose for CPU-only
        export COMPOSE_PROFILES="cpu"
    fi
fi

docker compose --env-file .env up -d 2>&1 | while read line; do echo "  $line"; done

echo ""
echo -e "${CYAN}[6/7] Waiting for services to be ready...${NC}"

# Wait for API
for i in $(seq 1 30); do
    if curl -sf http://localhost:8000/api/v1/health >/dev/null 2>&1; then
        echo -e "${GREEN}  ✅ API ready${NC}"
        break
    fi
    [ $i -eq 30 ] && echo -e "${YELLOW}  ⚠️  API still starting - check: docker compose logs api${NC}"
    sleep 2
done

# Wait for DB and run migrations
echo "  Running database migrations..."
docker compose exec -T api alembic upgrade head 2>&1 | tail -1 | while read line; do echo "    $line"; done
echo -e "${GREEN}  ✅ Database migrated${NC}"

# Pull Ollama model if needed
if [ "$LLM" = "ollama" ]; then
    echo "  Pulling Ollama model (this may take a few minutes on first run)..."
    docker compose exec -T ollama ollama pull llama3.2:8b 2>&1 | tail -2 | while read line; do echo "    $line"; done
    echo -e "${GREEN}  ✅ LLM model ready${NC}"
fi

# ─── Health Check ───
echo ""
echo -e "${CYAN}[7/7] Running health checks...${NC}"
echo ""

# Run the integration test
if [ -f tests/integration_test.sh ]; then
    bash tests/integration_test.sh 2>&1 | head -40
else
    # Quick inline check
    STATUS=$(curl -sf http://localhost:8000/api/v1/health 2>/dev/null || echo '{"status":"error"}')
    echo "  API Health: $STATUS"

    SCORE=$(curl -sf -X POST -H "Content-Type: application/json" \
        -d '{"cve_id":"CVE-2024-21887","cvss_base_score":9.1,"asset_tier":"tier_1","is_internet_facing":true}' \
        http://localhost:8000/api/v1/score 2>/dev/null || echo '{"error":"failed"}')
    echo "  Test Score: $SCORE"
fi

# ─── Done ───
echo ""
echo -e "${GREEN}${BOLD}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  🎉 VulnPilot AI is LIVE!                                   ║"
echo "║                                                              ║"
echo "║  Dashboard:  http://localhost:8000                           ║"
echo "║  API Docs:   http://localhost:8000/docs                      ║"
echo "║  Health:     http://localhost:8000/api/v1/health              ║"
echo "║                                                              ║"
echo "║  Run tests:  docker compose exec api python3 tests/run_tests.py"
echo "║  View logs:  docker compose logs -f                          ║"
echo "║  Stop:       docker compose down                             ║"
echo "║  Reconfigure: bash setup.sh                                  ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Open browser if possible
if command -v xdg-open >/dev/null 2>&1; then
    xdg-open http://localhost:8000 2>/dev/null &
elif command -v open >/dev/null 2>&1; then
    open http://localhost:8000 2>/dev/null &
fi
